services:
  tce-runtime:
    image: "tce-runtime-i"
    container_name: "tce-runtime-c"
    build:
      dockerfile: "./Dockerfile"
      context: "."
    environment:
      - TCE_MUX_TOKEN_ID=${TCE_MUX_TOKEN_ID}
      - TCE_MUX_TOKEN_SECRET=${TCE_MUX_TOKEN_SECRET}
      - TCE_MUX_JWT_SIGNING_KEY=${TCE_MUX_JWT_SIGNING_KEY}
      - TCE_MUX_JWT_PRIVATE_KEY=${TCE_MUX_JWT_PRIVATE_KEY}
    # Within docker network
    expose:
      - "8010"
      - "8020"
      - "8030"
      - "8080"
    # Within host
    ports:
      - "8010:8010"
      - "8020:8020"
      - "8030:8030"
      - "8080:8080"
