name: PR
on:
  push:
    branches: [ main, develop ]
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup pnpm and install deps
        uses: ./.github/actions/setup
      - name: Run linter
        run: pnpm lint
  e2e:
    runs-on: ubuntu-latest
    env:
      TCE_MUX_TOKEN_ID: ${{ secrets.TCE_MUX_TOKEN_ID }}
      TCE_MUX_TOKEN_SECRET: ${{ secrets.TCE_MUX_TOKEN_SECRET }}
      TCE_MUX_JWT_SIGNING_KEY: ${{ secrets.TCE_MUX_JWT_SIGNING_KEY }}
      TCE_MUX_JWT_PRIVATE_KEY: ${{ secrets.TCE_MUX_JWT_PRIVATE_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup pnpm and install deps
        uses: ./.github/actions/setup
      - name: Build packages
        run: pnpm build
      - name: Start runtime
        run: pnpm dev & sleep 50
      - name: Run E2E suite
        run: pnpm test
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: test/out
          retention-days: 30
